[build]
  base = "frontend"   
  publish = "."       
  command = ""

[[redirects]]
  from = "/"
  to   = "/home.html"
  status = 200

[[redirects]]
  from = "/index.html"
  to   = "/home.html"
  status = 200
