[build]
base = "frontend"
publish = "."
functions = "functions"   # <- relativo ao base => frontend/functions

[[redirects]]
from = "/_api/*"
to   = "/.netlify/functions/api-proxy/:splat"
status = 200
force = true
