# netlify.toml

[build]
  publish   = "."
  functions = "frontend/netlify/functions"


# 🔹 ESPECÍFICOS primeiro (vão direto para as Functions)

[[redirects]]
  from = "/_api/termo-solic-crp-pdf"
  to   = "/.netlify/functions/termo-solic-crp-pdf"
  status = 200

[[redirects]]
  from = "/_api/gerar-solic-crp"
  to   = "/.netlify/functions/gerar-solic-crp"
  status = 200

# 🔚 CATCH-ALL por último (tudo que sobrar vai para o proxy)
[[redirects]]
  from = "/_api/*"
  to   = "/.netlify/functions/api-proxy/:splat"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = [
    "@sparticuz/chromium",
    "puppeteer-core",
    "zod"
  ]

[functions."termo-solic-crp-pdf"]
  timeout = 26
  memory  = 1536

[functions."gerar-solic-crp"]
  timeout = 20
  memory  = 1024

[build.environment]
  NODE_VERSION = "20"
