[build]
  base = "frontend"
  functions = "functions"


[[redirects]]
  from = "/_api/*"
  to   = "/.netlify/functions/api-proxy/:splat"
  status = 200
  force  = true

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@sparticuz/chromium","puppeteer-core","zod"]
  timeout = 120
  memory = 1024