[build]
  publish   = "frontend"            # pasta com seus arquivos estáticos (index.html etc.)
  functions = "netlify/functions"   # pasta das funções (na raiz do repo)

[[redirects]]
  from = "/_api/termo-solic-crp-pdf"
  to   = "/.netlify/functions/termo-solic-crp-pdf"
  status = 200

[[redirects]]
  from = "/_api/gerar-solic-crp"
  to   = "/.netlify/functions/gerar-solic-crp"
  status = 200

[[redirects]]
  from = "/_api/gescon/termo-enc"
  to   = "/.netlify/functions/gescon-termo-enc"
  status = 200

[[redirects]]
  from = "/_api/termos-registrados"
  to   = "/.netlify/functions/termos-registrados"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@sparticuz/chromium", "puppeteer-core", "zod"]

[functions."termo-solic-crp-pdf"]
  timeout = 26
  memory  = 1536

[functions."gerar-solic-crp"]
  timeout = 20
  memory  = 1024

[functions."gescon-termo-enc"]
  timeout = 10
  memory  = 512

[functions."termos-registrados"]
  timeout = 10
  memory  = 512

[build.environment]
  NODE_VERSION = "20"
