[build]
  publish   = "."
  functions = "netlify/functions"

# === Funções específicas que você já usa (mantidas e vêm ANTES do catch-all) ===
[[redirects]]
  from = "/_api/termo-solic-crp-pdf"
  to   = "/.netlify/functions/termo-solic-crp-pdf"
  status = 200

[[redirects]]
  from = "/_api/gerar-solic-crp"
  to   = "/.netlify/functions/gerar-solic-crp"
  status = 200

[[redirects]]
  from = "/_api/gescon/termo-enc"
  to   = "/.netlify/functions/gescon-termo-enc"
  status = 200

[[redirects]]
  from = "/_api/termos-registrados"
  to   = "/.netlify/functions/termos-registrados"
  status = 200

# === PROXY GENÉRICO: redireciona TODO o resto de /_api/* para a função api-proxy ===
# (Isso cobre /_api/health, /_api/warmup, /_api/consulta, /_api/rep-by-cpf, /_api/termo-pdf, etc.)
[[redirects]]
  from = "/_api/*"
  to   = "/.netlify/functions/api-proxy/:splat"
  status = 200
  force  = true

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@sparticuz/chromium","puppeteer-core","zod"]

[functions."termo-solic-crp-pdf"]
  timeout = 26
  memory  = 1536

[functions."gerar-solic-crp"]
  timeout = 20
  memory  = 1024

[functions."gescon-termo-enc"]
  timeout = 10
  memory  = 512

[functions."termos-registrados"]
  timeout = 10
  memory  = 512

[build.environment]
  NODE_VERSION = "20"
