# Base directory = "frontend" no painel

[build]
  publish = "."
  functions = "netlify/functions"

# -------------------------
# Health/Diag (via api-proxy)
# -------------------------
[[redirects]]
  from = "/_api/health"
  to = "/.netlify/functions/api-proxy/health"
  status = 200

[[redirects]]
  from = "/_api/_diag"
  to = "/.netlify/functions/api-proxy/_diag"
  status = 200

# -------------------------
# Proxy catch-all auxiliar
# -------------------------
[[redirects]]
  from = "/_api/*"
  to = "/.netlify/functions/api-proxy/:splat"
  status = 200

# -------------------------------------------------------
# API: salvar via Function (api-proxy)  -> Render (seguro)
# -------------------------------------------------------
[[redirects]]
  from = "/api/gerar-solic-crp"
  to = "/.netlify/functions/api-proxy/gerar-solic-crp"
  status = 200

# -------------------------------------------------------
# API: PDF -> bypass direto ao Render (evita timeout)
# -------------------------------------------------------
[[redirects]]
  from = "/api/termo-solic-crp-pdf"
  to = "https://programa-de-regularidade.onrender.com/api/termo-solic-crp-pdf"
  status = 200
  force = true
  headers = { X-API-Key = "fprpps_5uP3rL0ng_", Origin = "https://programa-de-regularidade.netlify.app" }

# -------------------------
# Atalhos sem .html
# -------------------------
[[redirects]]
  from = "/form_gera_termo_adesao_1"
  to = "/form_gera_termo_adesao_1.html"
  status = 200

[[redirects]]
  from = "/form_gera_termo_solic_crp_2"
  to = "/form_gera_termo_solic_crp_2.html"
  status = 200

# -------------------------
# SPA fallback
# -------------------------
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# -------------------------
# Functions config (geral)
# -------------------------
[functions]
  node_bundler = "esbuild"

# (Removidos os blocks específicos "termo-solic-crp-pdf-v2" e "gerar-solic-crp"
#  pois o PDF agora vai direto ao Render e o salvar usa api-proxy.)

[build.environment]
  NODE_VERSION = "20"
  NODE_OPTIONS = "--max-old-space-size=3000"
