# netlify.toml — rotas específicas antes do curinga

[build]
  publish   = "."
  functions = "netlify/functions"

# === Functions locais (PDF + registrar) ===
[[redirects]]
  from = "/_api/termo-solic-crp-pdf-v2"
  to   = "/.netlify/functions/termo-solic-crp-pdf-v2"
  status = 200

[[redirects]]
  from = "/_api/termo-solic-crp-pdf"
  to   = "/.netlify/functions/termo-solic-crp-pdf"
  status = 200

[[redirects]]
  from = "/_api/gerar-solic-crp"
  to   = "/.netlify/functions/gerar-solic-crp"
  status = 200

# === Proxy para o backend (tudo mais) ===
[[redirects]]
  from = "/_api/*"
  to   = "/.netlify/functions/api-proxy/:splat"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@sparticuz/chromium","puppeteer-core","zod"]

# timeouts/memória dos PDFs
[functions."termo-solic-crp-pdf"]
  timeout = 26
  memory  = 1536

[functions."termo-solic-crp-pdf-v2"]
  timeout = 26
  memory  = 1536

[functions."gerar-solic-crp"]
  timeout = 20
  memory  = 1024

[build.environment]
  NODE_VERSION = "20"
