# netlify.toml — configuração ajustada

[build]
  publish   = "."
  # >>> IMPORTANTE: diretório real das funções no seu projeto
  functions = "frontend/netlify/functions"

# ========== Redirects ==========
# 1) Rotas ESPECÍFICAS (que têm função)
[[redirects]]
  from = "/_api/termo-solic-crp-pdf-v2"
  to   = "/.netlify/functions/termo-solic-crp-pdf-v2"
  status = 200

[[redirects]]
  from = "/_api/termo-solic-crp-pdf"
  to   = "/.netlify/functions/termo-solic-crp-pdf"
  status = 200

[[redirects]]
  from = "/_api/gerar-solic-crp"
  to   = "/.netlify/functions/gerar-solic-crp"
  status = 200

# 2) Curinga — tudo que não tiver rota específica acima cai no api-proxy
[[redirects]]
  from = "/_api/*"
  to   = "/.netlify/functions/api-proxy/:splat"
  status = 200

# ========== Funções ==========
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@sparticuz/chromium","puppeteer-core","zod"]

# Ajustes finos por função (tempo/memória)
[functions."termo-solic-crp-pdf-v2"]
  timeout = 26
  memory  = 1536

[functions."termo-solic-crp-pdf"]
  timeout = 26
  memory  = 1536

[functions."gerar-solic-crp"]
  timeout = 20
  memory  = 1024

[functions."api-proxy"]
  timeout = 20
  memory  = 512

# ========== Ambiente ==========
[build.environment]
  NODE_VERSION = "20"
