# netlify.toml — atualizado

[build]
  publish   = "."
  functions = "netlify/functions"

# ---- Rotas específicas do formulário de SOLICITAÇÃO de CRP (já existentes) ----
[[redirects]]
  from = "/_api/termo-solic-crp-pdf"
  to   = "/.netlify/functions/termo-solic-crp-pdf"
  status = 200

[[redirects]]
  from = "/_api/gerar-solic-crp"
  to   = "/.netlify/functions/gerar-solic-crp"
  status = 200

[[redirects]]
  from = "/_api/gescon/termo-enc"
  to   = "/.netlify/functions/gescon-termo-enc"
  status = 200

[[redirects]]
  from = "/_api/termos-registrados"
  to   = "/.netlify/functions/termos-registrados"
  status = 200

# ---- Catch-all para a API do formulário 1 (Adesão) via proxy ----
[[redirects]]
  from = "/_api/*"
  to   = "/.netlify/functions/api-prox/:splat"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@sparticuz/chromium","puppeteer-core","zod"]

[functions."termo-solic-crp-pdf"]
  timeout = 26
  memory  = 1536

[functions."gerar-solic-crp"]
  timeout = 20
  memory  = 1024

[functions."gescon-termo-enc"]
  timeout = 10
  memory  = 512

[functions."termos-registrados"]
  timeout = 10
  memory  = 512

# Config da função proxy do formulário 1
[functions."api-prox"]
  timeout = 20
  memory  = 512

[build.environment]
  NODE_VERSION = "20"
  # Defina no painel da Netlify:
  # API_BASE = "https://programa-de-regularidade.onrender.com"
  # API_KEY  = "fprpps_***************"
