# .github/workflows/keepalive.yml
name: Keep Render Free Awake
on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:
concurrency:
  group: keepalive
  cancel-in-progress: false
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl warmup
        run: |
          set -euxo pipefail
          curl -fsS "$URL/api/warmup" || true
    env:
      URL: https://programa-de-regularidade.onrender.com
